### ISSUE TITLE
2D-CTC Segmentation Fault

### ISSUE THREAD

**Issue by allenhu47** [Megvii-CSG/MegReader#1]
When I use the ctc_2d_loss, a segmentation fault appears. Any idea of what causes this problem? BTW, I am using CUDA9 and torch 1.0.

Also, I try to use the python implementation to train, but the accuracy is relatively low.

Thanks!

**Comment by wanzysky** [comment]
Can you provide more details about your environment and compiling? I test the CUDA implementation with CUDA9 and torch 1.1, and it works for me.

Can you show me the code using python implementation, as the api is different?

**Comment by allenhu47** [comment]
@wanzysky Thanks for your reply!

#### Using CUDA version
Hi, I am running the code on the server with GTX1080Ti. GCC compiler is "7.2.0", torch is "1.1.0", and nvcc is "V9.0.176" in the server environment.

After I have installed and builded the "setup.py" file in `\ops`, in the py file "ctc_loss_2d.py", the line `from . import ctc_2d_csrc` will rise the error "**ImportError: cannot import name 'ctc_2d_csrc**'".  Then I change the line `from . import ctc_2d_csrc` to `import ctc_2d_csrc`, which can successfully import ctc_2d_csrc.

I am not very familiar with CUDA compiling. Maybe it is because the compiler?

#### Using python version

I copy the file `MegReader/blob/master/decoders/ctc_loss2d.py` as my loss function.

Here is how I calculated loss:

```python
    def loss_compute_(self, hmap, outputs, labels, criterion):
        ctc_loss = CTCLoss2D()  ## from ctc_loss_2d import CTCLoss2D
        # Loss implemented using 2D CTC
        # initial hmap: # B x H x T
        # initial outputs : # B x C x H x T
        # initial labels: # B x L; labels are in the format [y1,y2,y3,y4,0,0,0,0,0,0]

        # New outputs_new [T, H, B, C]
        outputs_new = outputs.permute(3,2,0,1).contiguous()
        outputs_new = torch.log(torch.max(outputs_new, torch.tensor(1e-26).cuda()))

        # Height transition map [T x H x B]
        hmap = hmap.permute(2,1,0).contiguous()
        hmap = torch.log(torch.max(hmap, torch.tensor(1e-26).cuda()))

        # act_len
        act_len = outputs_new.size(0)
        act_lens = Variable(torch.IntTensor([act_len] * len(outputs)))

        # label_len
        label_len = labels.size(1)
        label_lens = Variable(torch.IntTensor([label_len] * len(labels)))

        # ctc_loss
        loss = ctc_loss(hmap, outputs_new, labels, act_lens, label_lens)

        return loss
```

Here is how I defined my model.

```python
class Model_CTC(nn.Module):
    """Implement of model with CTC
    """
    def __init__(self, arch, pretrained, num_classes):
        super(Model_CTC, self).__init__()
        self.num_classes = num_classes
        self.feat_size = NET_FACTORY[arch]['feat_size']
        self.encoder = Encoder(arch, pretrained, **kwargs)
        self.conv1 = nn.Conv2d(self.feat_size, self.feat_size//4, 3, padding=1)
        self.conv2 = nn.Conv2d(self.feat_size, self.feat_size//4, 3, padding=1)
        self.clf1 = nn.Conv2d(self.feat_size//4, self.num_classes, 1)
        self.clf2 = nn.Conv2d(self.feat_size//4, 1, 1)

    def forward(self, x):
        # encoder
        feat_seq = self.encoder(x) # B x C x H x T
        
        # decoder
        output = torch.softmax(self.clf1(self.conv1(feat_seq)), 1) # B x U x H x T
        hmap = torch.softmax(self.clf2(self.conv2(feat_seq)), 2) # B x 1 x  H x T
        
        return output, hmap.squeeze(1)
```

**Comment by wanzysky** [comment]
The segment fault may be caused by old version of gcc, we are using gcc 5.5.0.

**Comment by allenhu47** [comment]
I have tried gcc 5.3; 5.4; the segment fault still occurs. I will try to debug this.

For your python implementation of 2D-CTC loss，have you tried to train the recognition network using the implemented python ctc_2d_loss function? I cannot find anything wrong with it, but the accuracy keeps around 20%.

**Comment by wanzysky** [comment]
We validated the python implementation with the configuration in [yaml](https://github.com/Megvii-CSG/MegReader/blob/master/experiments/recognition/res50-ppm-2d-ctc.yaml). The performance was comparable with the CUDA version. 

We will try to reproduce the problem mentioned, any progress will be reported here.

**Comment by wanzysky** [comment]
```
act_lens = Variable(torch.IntTensor([act_len] * len(outputs)))
...
label_lens = Variable(torch.IntTensor([label_len] * len(labels)))
```

The generation of label lengths and prediction lengths is wrong. `label_lens` is supposed to be the corresponding lengths of each gt string, but not batch size nor maximum size. In your code, `len(outpus)` is also batch size.

**Comment by allenhu47** [comment]
The Segmentation Fault is solved by `python setup.py build & python setup.py install` and `I add .cuda() to all items which are passed to the ctc_2d_loss CUDA function`

For the python code I mentioned above, each label in a batch is padded with zeros to a fixed length to form the mini batch. 
```python
label_lens = Variable(torch.IntTensor([label_len] * len(labels)))
```
In this line, `label_len` the lengths of one GT string containing paddings, and `len(labels)` is the batch size. So the final variable `label_lens` which passed to the loss function is in a shape [N], with each item is the same.

In what way should I change the code, I am a bit lossed here. Thanks!

**Comment by allenhu47** [comment]
I will try to implement a new one with real GT labels length. Thanks!

**Comment by allenhu47** [comment]
```python
loss = self.ctc_loss(pred, targets.long(), input_lengths.long().to(
                pred.device), lengths.long()) / lengths.float()
```
@wanzysky
Sorry for asking you again.

Can you print an example of `targets` that is passed to the CUDA CTC-2D loss function? I am afraid my input is wrong.

```python
# Example of my 'targets'
        ([53, 59, 58, 56, 43, 39, 41, 46, 43, 42,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [39, 57, 51, 44, 41,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [57, 59, 45, 39, 56,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [44, 56, 53, 51, 26,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [57, 53, 51, 43,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [26,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [59, 50, 58, 56, 39, 50, 47, 45, 46, 58,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0],
        [51, 53, 56, 43,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
          0,  0]], device='cuda:4')

```

Currently, the loss won't decrease. My `pred` is the same as yours. My `targets` is in a shape as (Batch_Size x Max_Size) with zero paddings of every GT. My `input_lengths` is also the same as yours in a shape as (Batch). My `lengths` now contains real GT length which is in a shape as (Batch).

Also, I don't quite get how you form your GT labels in a mini batch. Is it by `torch.utils.data.dataloader.default_collate`?
