### ISSUE TITLE
Has this project been stopped for maintenance?

### ISSUE THREAD

**Issue by whuhangzhang** [Megvii-CSG/MegReader#19]
Has this project been stopped for maintenance? Want to ask a question, whether the future will duplicate TextScanner algorithm

**Comment by wanzysky** [comment]
Since the regulation of Megvii on source code sharing have changed, I can't just release code as what I did in last year. I am so sorry about that and will consider constructing another framework to implement related algorithm after my leaving Megvii.

**Comment by whuhangzhang** [comment]
Got it.
