### ISSUE TITLE
Will you update detection experiments configs?

### ISSUE THREAD

**Issue by zzdang** [Megvii-CSG/MegReader#3]
Hi, I see text-snake and east modules in your code, but I can't get their training configs? 
Will you update detection experiments configs?

**Comment by wanzysky** [comment]
Hi, @zzdang, thanks for your attention.
I think we are going to update the data and configs of these models in this month.

**Comment by zzdang** [comment]
Okey, thanks. I generate "meta.json" and detection experiment configs for text-snake, I can genrate "tr_mask, radius_map,sin_map..." by your code. But there are not textsnake backbone in your code?

**Comment by wanzysky** [comment]
As stated in the paper, TextSnake is compatible with a lot of backbones such as ResNet or VGG. I recommend ResNet with FPN, which is implemented in `backbones/resnet_fpn.py`.

**Comment by zzdang** [comment]
谢谢。目前training和eval都没问题，但做inference时可能需要改动TextsnakeDecoder和TextsnakeResultBuilder，因为这两块都需要lable dict中包含'tr_mask'，'tcl_mask' ，'sin_map' 'cos_map‘...这些key，请问后续会加入inference模块吗？
