### ISSUE TITLE
About 2 kinds of DenseConnection

### ISSUE THREAD

**Issue by wang2wei1** [Megvii-CSG/MegReader#4]
In `decoders/classification.py`, the shape of the input of the ClassificationDecoder (i.e. the output of the ClassificationBackbone) is (batch, channel, height, width). Before entring the fully connected layer, you make a global max 2D pooling to change the shape to (batch, channel). But a commonly used method is to flatten the 4D tensor of shape (batch, channel, height, width) to 2D shape  (batch, channel×height×width). Have you ever compared the two methods to transform the feature extraction output to fully connetion input? What effects will occur if we replace one method with another, such as the final accuraccy, or train/predict speed?

**Comment by wanzysky** [comment]
`decoders/classification.py` is the demo code for demonstrating the usage the framework of MegReader. It is designed for verification test of the effectiveness of the framework itself but not the specific performance of the network.
You can also conduct experiments to make further exploration and are welcome to post your conclusions here.
