### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by happog** [Megvii-CSG/MegReader#5]
hi, I use gcc 5.5 but the compile for 2d-ctc comes to error:

![image](https://user-images.githubusercontent.com/30194023/67371927-bbc76680-f5af-11e9-8c85-b20b2ad1b80d.png)

**Comment by Minwellcym** [comment]
Please check your environment variable [CUDA_HOME].
`>>> echo $CUDA_HOME`
If it's NULL, please set it to path_to_your_cuda_dir/cuda  e.g. "*/cuda9.0/cuda".
`export CUDA_HOME=path_to_your_cuda_dir/cuda`
For convenience, you could add this to your bashrc.

**Comment by happog** [comment]
Thank you! it is solved. One more question: do you have a plant to release the cpu version of 2d-ctc operator?
